"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { apiFetch } from "@/lib/api";
import { getToken } from "@/lib/auth";
import { BarChart3, BookOpen, CheckCircle2, ChevronLeft, CircleDollarSign, GraduationCap, LayoutDashboard, LockKeyhole, Plus, Save, ShieldCheck, Trash2, Users, X } from "lucide-react";

const money = (n: number) => new Intl.NumberFormat("fa-IR").format(Math.round(n)) + " تومان";
const date = (s: string) => new Intl.DateTimeFormat("fa-IR", { dateStyle: "medium" }).format(new Date(s));

type Stats = { courses:number; publishedCourses:number; students:number; enrollments:number; paidOrders:number; totalRevenue:number; successfulPayments:number; pendingPayments:number };
type Category = { id:string; name:string; slug:string };
type Course = { id:string; title:string; slug:string; description:string; price:number; thumbnailUrl?:string; isPublished:boolean; lessonsCount:number; studentsCount:number; revenue:number; category:{id:string;name:string} };
type Lesson = { id:string; title:string; description?:string; order:number; durationInMinutes:number; videoId?:string; isFree:boolean };
type Payment = { id:string; orderId:string; amount:number; referenceId?:string; isSuccessful:boolean; createdAt:string; paidAt?:string; status:string; user?:{email:string;firstName:string;lastName:string}; courses:{courseId:string;title:string}[] };
type Student = { userId:string; courses:number; lastEnrolledAt:string; averageProgress:number; user?:{email:string;firstName:string;lastName:string} };

function isTeacherToken() {
  const token = getToken();
  if (!token) return false;
  try {
    const payload = JSON.parse(atob(token.split(".")[1].replace(/-/g,"+").replace(/_/g,"/")));
    const role = payload.role ?? payload["http://schemas.microsoft.com/ws/2008/06/identity/claims/role"];
    return role === "Teacher" || (Array.isArray(role) && role.includes("Teacher")) || role === "Admin";
  } catch { return false; }
}

export default function TeacherPanel() {
  const [allowed,setAllowed] = useState<boolean|null>(null);
  const [tab,setTab] = useState("overview");
  const [stats,setStats] = useState<Stats|null>(null);
  const [courses,setCourses] = useState<Course[]>([]);
  const [payments,setPayments] = useState<Payment[]>([]);
  const [students,setStudents] = useState<Student[]>([]);
  const [categories,setCategories] = useState<Category[]>([]);
  const [selected,setSelected] = useState<Course|null>(null);
  const [lessons,setLessons] = useState<Lesson[]>([]);
  const [showCourse,setShowCourse] = useState(false);
  const [saving,setSaving] = useState(false);
  const [message,setMessage] = useState("");

  useEffect(()=>{ const ok=isTeacherToken(); setAllowed(ok); if(ok) load(); },[]);
  async function load(){
    try { const [s,c,p,u,cat]=await Promise.all([apiFetch<Stats>("/teacher/dashboard"),apiFetch<Course[]>("/teacher/courses"),apiFetch<{items:Payment[]}>("/teacher/payments?pageSize=50"),apiFetch<{items:Student[]}>("/teacher/students?pageSize=50"),apiFetch<Category[]>("/teacher/categories")]); setStats(s);setCourses(c);setPayments(p.items);setStudents(u.items);setCategories(cat); } catch(e:any){ setMessage(e.message||"خطا در دریافت اطلاعات"); }
  }
  async function openCourse(c:Course){ try { const x=await apiFetch<{lessons:Lesson[]}>(`/teacher/courses/${c.id}`); setSelected(c);setLessons(x.lessons);setTab("lessons"); } catch(e:any){setMessage(e.message)} }
  async function archive(id:string){ if(!confirm("این دوره از انتشار خارج شود؟ اطلاعات و خریدهای قبلی حذف نمی‌شوند.")) return; await apiFetch(`/teacher/courses/${id}`,{method:"DELETE"}); await load(); setMessage("دوره با موفقیت از انتشار خارج شد."); }
  if(allowed===null) return <main className="min-h-screen grid place-items-center bg-[#fbf8f4]">در حال بررسی دسترسی...</main>;
  if(!allowed) return <main className="min-h-screen grid place-items-center bg-[#fbf8f4] p-6"><div className="max-w-md rounded-[32px] bg-white p-10 text-center shadow-xl"><LockKeyhole className="mx-auto h-12 w-12 text-[#b78b72]"/><h1 className="mt-5 text-2xl font-black">دسترسی محدود</h1><p className="mt-3 leading-8 text-gray-500">این بخش فقط برای استاد یا مدیر سامانه فعال است. مجوز در سمت سرور نیز بررسی می‌شود.</p></div></main>;
  return <main dir="rtl" className="min-h-screen bg-[#f7f2ed] text-[#211d1a]">
    <header className="bg-[#211d1a] text-white"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-4 py-5 sm:flex-row sm:items-center sm:justify-between sm:px-5"><div><p className="text-xs font-bold tracking-[.25em] text-[#d8c1b3]">NAILCOURSE • INSTRUCTOR</p><h1 className="mt-1 text-2xl font-black">پنل ویژه استاد</h1></div><div className="flex w-fit items-center gap-3 rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs sm:text-sm"><ShieldCheck className="h-4 w-4 text-[#d8c1b3]"/> دسترسی محافظت‌شده</div></div></header>
    <div className="mx-auto grid max-w-7xl gap-5 px-4 py-5 sm:px-5 sm:py-7 lg:grid-cols-[230px_1fr]">
      <aside className="h-fit rounded-[28px] bg-white p-2 shadow-sm lg:sticky lg:top-24 lg:p-3"><Nav active={tab} setActive={setTab}/></aside>
      <section className="min-w-0">
        {message && <div className="mb-5 flex items-center justify-between rounded-2xl border border-[#d8c1b3] bg-[#fffaf7] px-4 py-3 text-sm"><span>{message}</span><button onClick={()=>setMessage("")}><X className="h-4 w-4"/></button></div>}
        {tab==="overview" && <Overview stats={stats} courses={courses} payments={payments} />}
        {tab==="courses" && <Courses courses={courses} onAdd={()=>setShowCourse(true)} onOpen={openCourse} onArchive={archive}/>} 
        {tab==="lessons" && <Lessons course={selected} lessons={lessons} onBack={()=>setTab("courses")} reload={()=>selected&&openCourse(selected)} setMessage={setMessage}/>} 
        {tab==="payments" && <Payments rows={payments}/>} 
        {tab==="students" && <Students rows={students}/>} 
        {tab==="security" && <Security/>}
      </section>
    </div>
    {showCourse && <CourseModal categories={categories} onClose={()=>setShowCourse(false)} onSaved={async()=>{setShowCourse(false);await load();setMessage("دوره ایجاد شد.")}}/>}
  </main>
}

function Nav({active,setActive}:{active:string;setActive:(x:string)=>void}){const items=[['overview','داشبورد',LayoutDashboard],['courses','دوره‌ها',BookOpen],['payments','پرداخت‌ها',CircleDollarSign],['students','هنرجویان',Users],['security','امنیت',ShieldCheck]] as const;return <nav className="flex gap-1 overflow-x-auto pb-1 lg:block lg:space-y-1">{items.map(([id,label,I])=><button key={id} onClick={()=>setActive(id)} className={`flex min-w-max items-center gap-3 rounded-2xl px-4 py-3 text-sm font-bold transition ${active===id?'bg-[#b78b72] text-white':'text-gray-600 hover:bg-[#f5eee9]'}`}><I className="h-4 w-4"/>{label}</button>)}</nav>}

function Overview({stats,courses,payments}:{stats:Stats|null;courses:Course[];payments:Payment[]}){return <div><div className="mb-6 flex items-end justify-between"><div><p className="text-sm font-bold text-[#b78b72]">نمای کلی کسب‌وکار</p><h2 className="mt-1 text-3xl font-black">مدیریت آموزشگاه</h2></div></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["دوره‌ها",stats?.courses??0,BookOpen],["هنرجوی فعال",stats?.students??0,GraduationCap],["فروش موفق",stats?.paidOrders??0,CheckCircle2],["درآمد",money(stats?.totalRevenue??0),CircleDollarSign]].map(([l,v,I]:any)=><div key={l} className="rounded-[26px] bg-white p-5 shadow-sm"><I className="h-5 w-5 text-[#b78b72]"/><p className="mt-5 text-sm text-gray-500">{l}</p><p className="mt-1 text-2xl font-black">{v}</p></div>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-2"><div className="rounded-[28px] bg-white p-6"><h3 className="font-black">دوره‌های پرفروش</h3><div className="mt-5 space-y-4">{courses.slice(0,5).map(c=><div key={c.id} className="flex items-center justify-between border-b pb-4 last:border-0"><div><b>{c.title}</b><p className="mt-1 text-xs text-gray-400">{c.studentsCount} هنرجو</p></div><b className="text-sm">{money(c.revenue)}</b></div>)}</div></div><div className="rounded-[28px] bg-white p-6"><h3 className="font-black">آخرین پرداخت‌ها</h3><div className="mt-5 space-y-4">{payments.slice(0,5).map(p=><div key={p.id} className="flex items-center justify-between border-b pb-4 last:border-0"><div><b>{p.user?.firstName} {p.user?.lastName}</b><p className="mt-1 text-xs text-gray-400">{p.courses.map(c=>c.title).join("، ")}</p></div><span className="text-sm font-black">{money(p.amount)}</span></div>)}</div></div></div></div>}

function Courses({courses,onAdd,onOpen,onArchive}:{courses:Course[];onAdd:()=>void;onOpen:(c:Course)=>void;onArchive:(id:string)=>void}){return <div><div className="mb-6 flex items-center justify-between"><div><h2 className="text-3xl font-black">دوره‌های من</h2><p className="mt-2 text-sm text-gray-500">ساخت، انتشار و مدیریت محتوای آموزشی</p></div><button onClick={onAdd} className="inline-flex items-center gap-2 rounded-full bg-[#b78b72] px-5 py-3 text-sm font-black text-white transition hover:bg-[#8d6a55]"><Plus className="h-4 w-4"/> دوره جدید</button></div><div className="overflow-hidden rounded-[28px] bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full text-right text-sm"><thead className="bg-[#faf6f2] text-gray-500"><tr><th className="p-4">دوره</th><th>هنرجو</th><th>درآمد</th><th>وضعیت</th><th></th></tr></thead><tbody>{courses.map(c=><tr key={c.id} className="border-t"><td className="p-4"><b>{c.title}</b><p className="mt-1 text-xs text-gray-400">{c.lessonsCount} درس</p></td><td>{c.studentsCount}</td><td>{money(c.revenue)}</td><td><span className={`rounded-full px-3 py-1 text-xs font-bold ${c.isPublished?'bg-green-50 text-green-700':'bg-gray-100 text-gray-500'}`}>{c.isPublished?'منتشر شده':'پیش‌نویس'}</span></td><td><div className="flex gap-2"><button onClick={()=>onOpen(c)} className="rounded-full bg-[#f4ece6] px-3 py-2 text-xs font-bold">مدیریت محتوا</button>{c.isPublished&&<button onClick={()=>onArchive(c.id)} className="rounded-full bg-red-50 px-3 py-2 text-xs font-bold text-red-700">عدم انتشار</button>}</div></td></tr>)}</tbody></table></div></div></div>}

function Lessons({course,lessons,onBack,reload,setMessage}:{course:Course|null;lessons:Lesson[];onBack:()=>void;reload:()=>void;setMessage:(x:string)=>void}){const [open,setOpen]=useState(false);if(!course)return <div className="rounded-[28px] bg-white p-8"><p>ابتدا یک دوره را انتخاب کنید.</p><button onClick={onBack} className="mt-4">بازگشت</button></div>;return <div><button onClick={onBack} className="mb-5 inline-flex items-center gap-2 text-sm font-bold"><ChevronLeft className="h-4 w-4"/> بازگشت به دوره‌ها</button><div className="mb-6 flex items-center justify-between"><div><h2 className="text-3xl font-black">{course.title}</h2><p className="mt-2 text-sm text-gray-500">مدیریت فصل‌ها و ویدئوهای دوره</p></div><button onClick={()=>setOpen(true)} className="inline-flex items-center gap-2 rounded-full bg-[#b78b72] px-5 py-3 text-sm font-black text-white transition hover:bg-[#8d6a55]"><Plus className="h-4 w-4"/> افزودن درس</button></div><div className="space-y-3">{lessons.map(l=><div key={l.id} className="flex items-center justify-between rounded-[22px] bg-white p-5 shadow-sm"><div><p className="font-black">{l.order}. {l.title}</p><p className="mt-1 text-xs text-gray-400">{l.durationInMinutes} دقیقه • {l.isFree?'رایگان':'ویژه هنرجو'} {l.videoId?`• ${l.videoId}`:''}</p></div><button onClick={async()=>{if(!confirm('این درس حذف شود؟'))return;await apiFetch(`/teacher/lessons/${l.id}`,{method:'DELETE'});reload();setMessage('درس حذف شد.')}} className="rounded-full bg-red-50 p-3 text-red-700"><Trash2 className="h-4 w-4"/></button></div>)}</div>{open&&<LessonModal courseId={course.id} nextOrder={lessons.length+1} onClose={()=>setOpen(false)} onSaved={()=>{setOpen(false);reload();setMessage('درس اضافه شد.')}}/>}</div>}

function CourseModal({categories,onClose,onSaved}:{categories:Category[];onClose:()=>void;onSaved:()=>void}){const [f,setF]=useState({categoryId:categories[0]?.id??'',title:'',slug:'',description:'',price:'',thumbnailUrl:'',isPublished:true});const [err,setErr]=useState('');async function submit(e:FormEvent){e.preventDefault();try{await apiFetch('/teacher/courses',{method:'POST',body:JSON.stringify({...f,price:Number(f.price)})});onSaved()}catch(e:any){setErr(e.message)}}return <Modal title="ایجاد دوره جدید" onClose={onClose}><form onSubmit={submit} className="space-y-4"><Input label="عنوان دوره" value={f.title} onChange={v=>setF({...f,title:v})} required/><Input label="Slug انگلیسی" value={f.slug} onChange={v=>setF({...f,slug:v})} required/><select className="w-full rounded-xl border p-3" value={f.categoryId} onChange={e=>setF({...f,categoryId:e.target.value})}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><Input label="قیمت (تومان)" type="number" value={f.price} onChange={v=>setF({...f,price:v})} required/><Input label="آدرس تصویر" value={f.thumbnailUrl} onChange={v=>setF({...f,thumbnailUrl:v})}/><textarea className="min-h-28 w-full rounded-xl border p-3" placeholder="توضیحات دوره" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/>{err&&<p className="text-sm text-red-600">{err}</p>}<button className="w-full rounded-full bg-[#b78b72] py-3 font-black text-white transition hover:bg-[#8d6a55]"><Save className="ml-2 inline h-4 w-4"/>ذخیره دوره</button></form></Modal>}
function LessonModal({courseId,nextOrder,onClose,onSaved}:{courseId:string;nextOrder:number;onClose:()=>void;onSaved:()=>void}){const [f,setF]=useState({title:'',description:'',order:String(nextOrder),durationInMinutes:'10',videoId:'',isFree:false});const [err,setErr]=useState('');async function submit(e:FormEvent){e.preventDefault();try{await apiFetch(`/teacher/courses/${courseId}/lessons`,{method:'POST',body:JSON.stringify({...f,order:Number(f.order),durationInMinutes:Number(f.durationInMinutes)})});onSaved()}catch(e:any){setErr(e.message)}}return <Modal title="افزودن درس" onClose={onClose}><form onSubmit={submit} className="space-y-4"><Input label="عنوان درس" value={f.title} onChange={v=>setF({...f,title:v})} required/><Input label="شماره" type="number" value={f.order} onChange={v=>setF({...f,order:v})}/><Input label="مدت (دقیقه)" type="number" value={f.durationInMinutes} onChange={v=>setF({...f,durationInMinutes:v})}/><Input label="Video ID" value={f.videoId} onChange={v=>setF({...f,videoId:v})}/><textarea className="min-h-24 w-full rounded-xl border p-3" placeholder="توضیح درس" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={f.isFree} onChange={e=>setF({...f,isFree:e.target.checked})}/> درس رایگان</label>{err&&<p className="text-sm text-red-600">{err}</p>}<button className="w-full rounded-full bg-[#b78b72] py-3 font-black text-white transition hover:bg-[#8d6a55]">ذخیره درس</button></form></Modal>}
function Input({label,value,onChange,type='text',required=false}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean}){return <label className="block text-sm font-bold">{label}<input required={required} type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-xl border p-3 font-normal outline-none focus:border-[#b78b72]"/></label>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><div className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-[30px] bg-white p-7"><div className="mb-6 flex items-center justify-between"><h3 className="text-xl font-black">{title}</h3><button onClick={onClose}><X/></button></div>{children}</div></div>}
function Payments({rows}:{rows:Payment[]}){return <div><h2 className="mb-6 text-3xl font-black">پرداخت‌ها</h2><div className="overflow-hidden rounded-[28px] bg-white"><div className="overflow-x-auto"><table className="w-full text-right text-sm"><thead className="bg-[#faf6f2]"><tr><th className="p-4">هنرجو</th><th>دوره</th><th>مبلغ</th><th>وضعیت</th><th>تاریخ</th><th>کد پیگیری</th></tr></thead><tbody>{rows.map(p=><tr className="border-t" key={p.id}><td className="p-4"><b>{p.user?.firstName} {p.user?.lastName}</b><p className="text-xs text-gray-400">{p.user?.email}</p></td><td>{p.courses.map(c=>c.title).join('، ')}</td><td>{money(p.amount)}</td><td><span className={p.isSuccessful?'text-green-700':'text-red-700'}>{p.isSuccessful?'موفق':'ناموفق'}</span></td><td>{date(p.createdAt)}</td><td>{p.referenceId||'—'}</td></tr>)}</tbody></table></div></div></div>}
function Students({rows}:{rows:Student[]}){return <div><h2 className="mb-6 text-3xl font-black">هنرجویان</h2><div className="overflow-hidden rounded-[28px] bg-white"><div className="overflow-x-auto"><table className="w-full text-right text-sm"><thead className="bg-[#faf6f2]"><tr><th className="p-4">هنرجو</th><th>دوره‌ها</th><th>میانگین پیشرفت</th><th>آخرین ثبت‌نام</th></tr></thead><tbody>{rows.map(s=><tr className="border-t" key={s.userId}><td className="p-4"><b>{s.user?.firstName} {s.user?.lastName}</b><p className="text-xs text-gray-400">{s.user?.email}</p></td><td>{s.courses}</td><td>{Math.round(s.averageProgress)}٪</td><td>{date(s.lastEnrolledAt)}</td></tr>)}</tbody></table></div></div></div>}
function Security(){return <div className="max-w-3xl"><h2 className="mb-6 text-3xl font-black">امنیت پنل</h2><div className="space-y-4"><div className="rounded-[28px] bg-white p-6"><div className="flex gap-4"><ShieldCheck className="h-6 w-6 text-[#b78b72]"/><div><b>مجوز سمت سرور</b><p className="mt-2 text-sm leading-7 text-gray-500">تمام APIهای این پنل با نقش Teacher/Admin محافظت می‌شوند؛ مخفی کردن دکمه‌ها در فرانت‌اند به‌تنهایی معیار امنیت نیست.</p></div></div></div><div className="rounded-[28px] bg-white p-6"><div className="flex gap-4"><LockKeyhole className="h-6 w-6 text-[#b78b72]"/><div><b>عدم حذف مخرب</b><p className="mt-2 text-sm leading-7 text-gray-500">حذف دوره در پنل به «عدم انتشار» تبدیل شده تا خریدها و دسترسی‌های قبلی به‌صورت ناخواسته حذف نشوند.</p></div></div></div></div></div>}
